//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientHelpCare.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int CertificateId { get; set; }
        public string ProfessionalCertificateorAward { get; set; }
        public string ConferringOrganization { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public string DoctorId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
