//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientHelpCare.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamber
    {
        public int ChamberId { get; set; }
        public string Name { get; set; }
        public string FromDay { get; set; }
        public string ToDay { get; set; }
        public string StartTime { get; set; }
        public string Endtime { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int ZipCode { get; set; }
        public string DoctorId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
