//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientHelpCare.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Doctor_InformationEntities : DbContext
    {
        public Doctor_InformationEntities()
            : base("name=Doctor_InformationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Experience> Experiences { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Chamber> Chambers { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
    }
}
